### PR TITLE
Add diagrams for provider OVS scenario

### PR DESCRIPTION
**Pull request by ionosphere80**
Add diagrams for provider networks scenario with Open vSwitch.

### CODE REVIEW

**Comment by sc68cal** [comment]
Small error in ` common/images/scenario-provider-ovs/networkguide-neutron-provider-ovs-services.png ` - the "Networking ML2 plugin" needs to be on the controller node, not the compute node. Otherwise looks good so far!

**Comment by sc68cal** [comment]
Also, the controller doesn't need to run the "Networking Open vSwitch agent" if it isn't running the compute service on it, on the ` common/images/scenario-provider-ovs/networkguide-neutron-provider-ovs-services.png ` diagram.

**Comment by ionosphere80** [comment]
I thought both the controller and compute nodes require the ML2 plug-in and OVS agent because they manages switches and namespaces (DHCP).

**Comment by sc68cal** [comment]
No. The Computes only need the `ovs-neutron-agent` running, while the controller runs the ML2 plugin (and Neutron API server). The DHCP namespace is handled by the `neutron-dhcp-agent` binary. The controller only needs to run the `ovs-neutron-agent` if it is also going to be a hypervisor and run guests. 

In a provider networking scenario, if you are only doing provider nets and using a hardware or external service for L3, you do not run the `neutron-l3-agent` at all, nor the metadata agent

**Comment by sc68cal** [comment]
:+1: for merge

**Pull request merged**
